#ifndef MEDIANFILTER_GLOBAL_H
#define MEDIANFILTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MEDIANFILTER_LIBRARY)
#  define MEDIANFILTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MEDIANFILTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MEDIANFILTER_GLOBAL_H
